const CandidateLocalData=[
    {
      "name": "John Doe",
      "domain": ["webdevelopment"],
      "kiitemail": "johndoe18@kiit.ac.in",
      "email": "john.doe@gmail.com",
      "roll": 1234567,
      "gender": "Male",
      "contactNumber": 9876543210,
      "yearOfStudy": "2nd",
      "branch": "Computer Science",
      "links": {
        "resume": "https://example.com/resume/johndoe",
        "github": "https://github.com/johndoe",
        "linkdin": "https://linkedin.com/in/johndoe"
      },
      "existSocieties": "None",
      "whyElabs": "To improve my technical skills and work on innovative projects.",
      "fromWhereYouGotKnow": "Social Media",
      "anythingElse": "Looking forward to learning new technologies.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Thank you for considering my application."
    },
    {
      "name": "Jane Smith",
      "domain": ["graphicdesigning"],
      "kiitemail": "janesmith18@kiit.ac.in",
      "email": "jane.smith@gmail.com",
      "roll": 1234568,
      "gender": "Female",
      "contactNumber": 9876543211,
      "yearOfStudy": "3rd",
      "branch": "Information Technology",
      "links": {
        "resume": "https://example.com/resume/janesmith",
        "github": "https://github.com/janesmith",
        "linkdin": "https://linkedin.com/in/janesmith"
      },
      "existSocieties": "Art Society",
      "whyElabs": "To contribute my design skills and collaborate with others.",
      "fromWhereYouGotKnow": "Friends",
      "anythingElse": "Excited to join and learn!",
      "present": true,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Looking forward to hearing from you."
    },
    {
      "name": "Chris Johnson",
      "domain": ["iot"],
      "kiitemail": "chrisjohnson18@kiit.ac.in",
      "email": "chris.johnson@gmail.com",
      "roll": 1234569,
      "gender": "Male",
      "contactNumber": 9876543212,
      "yearOfStudy": "4th",
      "branch": "Electronics and Communication",
      "links": {
        "resume": "https://example.com/resume/chrisjohnson",
        "github": "https://github.com/chrisjohnson",
        "linkdin": "https://linkedin.com/in/chrisjohnson"
      },
      "existSocieties": "Robotics Club",
      "whyElabs": "To explore IoT and work on interdisciplinary projects.",
      "fromWhereYouGotKnow": "Faculty",
      "anythingElse": "Hoping to contribute meaningfully.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Thank you for this opportunity."
    },
    {
      "name": "Alex Taylor",
      "domain": ["gamedevelopment"],
      "kiitemail": "alextaylor18@kiit.ac.in",
      "email": "alex.taylor@gmail.com",
      "roll": 1234570,
      "gender": "Female",
      "contactNumber": 9876543213,
      "yearOfStudy": "1st",
      "branch": "Computer Science",
      "links": {
        "resume": "https://example.com/resume/alextaylor",
        "github": "https://github.com/alextaylor",
        "linkdin": "https://linkedin.com/in/alextaylor"
      },
      "existSocieties": "Gaming Club",
      "whyElabs": "To create immersive gaming experiences and learn with peers.",
      "fromWhereYouGotKnow": "Website",
      "anythingElse": "Passionate about game design.",
      "present": false,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Eager to start my journey at Elabs."
    },
    {
      "name": "Taylor Morgan",
      "domain": ["videoediting"],
      "kiitemail": "taylormorgan18@kiit.ac.in",
      "email": "taylor.morgan@gmail.com",
      "roll": 1234571,
      "gender": "Male",
      "contactNumber": 9876543214,
      "yearOfStudy": "3rd",
      "branch": "Mass Communication",
      "links": {
        "resume": "https://example.com/resume/taylormorgan",
        "github": "https://github.com/taylormorgan",
        "linkdin": "https://linkedin.com/in/taylormorgan"
      },
      "existSocieties": "Film Club",
      "whyElabs": "To hone my video editing skills and create impactful stories.",
      "fromWhereYouGotKnow": "Friends",
      "anythingElse": "Looking forward to collaborating with others.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": true,
      "selectedBy": "Panel A",
      "message": "Thank you for selecting me."
    },
    {
      "name": "Jordan Casey",
      "domain": ["marketing"],
      "kiitemail": "jordancasey18@kiit.ac.in",
      "email": "jordan.casey@gmail.com",
      "roll": 1234572,
      "gender": "Female",
      "contactNumber": 9876543215,
      "yearOfStudy": "4th",
      "branch": "Business Administration",
      "links": {
        "resume": "https://example.com/resume/jordancasey",
        "github": "https://github.com/jordancasey",
        "linkdin": "https://linkedin.com/in/jordancasey"
      },
      "existSocieties": "Marketing Society",
      "whyElabs": "To apply my marketing knowledge in tech-oriented projects.",
      "fromWhereYouGotKnow": "Alumni",
      "anythingElse": "Excited to bring my creative ideas to the team.",
      "present": true,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Looking forward to contributing."
    },
    {
      "name": "John Doe",
      "domain": ["webdevelopment"],
      "kiitemail": "johndoe18@kiit.ac.in",
      "email": "john.doe@gmail.com",
      "roll": 1234567,
      "gender": "Male",
      "contactNumber": 9876543210,
      "yearOfStudy": "2nd",
      "branch": "Computer Science",
      "links": {
        "resume": "https://example.com/resume/johndoe",
        "github": "https://github.com/johndoe",
        "linkdin": "https://linkedin.com/in/johndoe"
      },
      "existSocieties": "None",
      "whyElabs": "To improve my technical skills and work on innovative projects.",
      "fromWhereYouGotKnow": "Social Media",
      "anythingElse": "Looking forward to learning new technologies.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Thank you for considering my application."
    },
    {
      "name": "Jane Smith",
      "domain": ["graphicdesigning"],
      "kiitemail": "janesmith18@kiit.ac.in",
      "email": "jane.smith@gmail.com",
      "roll": 1234568,
      "gender": "Female",
      "contactNumber": 9876543211,
      "yearOfStudy": "3rd",
      "branch": "Information Technology",
      "links": {
        "resume": "https://example.com/resume/janesmith",
        "github": "https://github.com/janesmith",
        "linkdin": "https://linkedin.com/in/janesmith"
      },
      "existSocieties": "Art Society",
      "whyElabs": "To contribute my design skills and collaborate with others.",
      "fromWhereYouGotKnow": "Friends",
      "anythingElse": "Excited to join and learn!",
      "present": true,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Looking forward to hearing from you."
    },
    {
      "name": "Chris Johnson",
      "domain": ["iot"],
      "kiitemail": "chrisjohnson18@kiit.ac.in",
      "email": "chris.johnson@gmail.com",
      "roll": 1234569,
      "gender": "Male",
      "contactNumber": 9876543212,
      "yearOfStudy": "4th",
      "branch": "Electronics and Communication",
      "links": {
        "resume": "https://example.com/resume/chrisjohnson",
        "github": "https://github.com/chrisjohnson",
        "linkdin": "https://linkedin.com/in/chrisjohnson"
      },
      "existSocieties": "Robotics Club",
      "whyElabs": "To explore IoT and work on interdisciplinary projects.",
      "fromWhereYouGotKnow": "Faculty",
      "anythingElse": "Hoping to contribute meaningfully.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Thank you for this opportunity."
    },
    {
      "name": "Alex Taylor",
      "domain": ["gamedevelopment"],
      "kiitemail": "alextaylor18@kiit.ac.in",
      "email": "alex.taylor@gmail.com",
      "roll": 1234570,
      "gender": "Female",
      "contactNumber": 9876543213,
      "yearOfStudy": "1st",
      "branch": "Computer Science",
      "links": {
        "resume": "https://example.com/resume/alextaylor",
        "github": "https://github.com/alextaylor",
        "linkdin": "https://linkedin.com/in/alextaylor"
      },
      "existSocieties": "Gaming Club",
      "whyElabs": "To create immersive gaming experiences and learn with peers.",
      "fromWhereYouGotKnow": "Website",
      "anythingElse": "Passionate about game design.",
      "present": false,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Eager to start my journey at Elabs."
    },
    {
      "name": "Taylor Morgan",
      "domain": ["videoediting"],
      "kiitemail": "taylormorgan18@kiit.ac.in",
      "email": "taylor.morgan@gmail.com",
      "roll": 1234571,
      "gender": "Male",
      "contactNumber": 9876543214,
      "yearOfStudy": "3rd",
      "branch": "Mass Communication",
      "links": {
        "resume": "https://example.com/resume/taylormorgan",
        "github": "https://github.com/taylormorgan",
        "linkdin": "https://linkedin.com/in/taylormorgan"
      },
      "existSocieties": "Film Club",
      "whyElabs": "To hone my video editing skills and create impactful stories.",
      "fromWhereYouGotKnow": "Friends",
      "anythingElse": "Looking forward to collaborating with others.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": true,
      "selectedBy": "Panel A",
      "message": "Thank you for selecting me."
    },
    {
      "name": "Jordan Casey",
      "domain": ["marketing"],
      "kiitemail": "jordancasey18@kiit.ac.in",
      "email": "jordan.casey@gmail.com",
      "roll": 1234572,
      "gender": "Female",
      "contactNumber": 9876543215,
      "yearOfStudy": "4th",
      "branch": "Business Administration",
      "links": {
        "resume": "https://example.com/resume/jordancasey",
        "github": "https://github.com/jordancasey",
        "linkdin": "https://linkedin.com/in/jordancasey"
      },
      "existSocieties": "Marketing Society",
      "whyElabs": "To apply my marketing knowledge in tech-oriented projects.",
      "fromWhereYouGotKnow": "Alumni",
      "anythingElse": "Excited to bring my creative ideas to the team.",
      "present": true,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Looking forward to contributing."
    },
    {
      "name": "John Doe",
      "domain": ["webdevelopment"],
      "kiitemail": "johndoe18@kiit.ac.in",
      "email": "john.doe@gmail.com",
      "roll": 1234567,
      "gender": "Male",
      "contactNumber": 9876543210,
      "yearOfStudy": "2nd",
      "branch": "Computer Science",
      "links": {
        "resume": "https://example.com/resume/johndoe",
        "github": "https://github.com/johndoe",
        "linkdin": "https://linkedin.com/in/johndoe"
      },
      "existSocieties": "None",
      "whyElabs": "To improve my technical skills and work on innovative projects.",
      "fromWhereYouGotKnow": "Social Media",
      "anythingElse": "Looking forward to learning new technologies.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Thank you for considering my application."
    },
    {
      "name": "Jane Smith",
      "domain": ["graphicdesigning"],
      "kiitemail": "janesmith18@kiit.ac.in",
      "email": "jane.smith@gmail.com",
      "roll": 1234568,
      "gender": "Female",
      "contactNumber": 9876543211,
      "yearOfStudy": "3rd",
      "branch": "Information Technology",
      "links": {
        "resume": "https://example.com/resume/janesmith",
        "github": "https://github.com/janesmith",
        "linkdin": "https://linkedin.com/in/janesmith"
      },
      "existSocieties": "Art Society",
      "whyElabs": "To contribute my design skills and collaborate with others.",
      "fromWhereYouGotKnow": "Friends",
      "anythingElse": "Excited to join and learn!",
      "present": true,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Looking forward to hearing from you."
    },
    {
      "name": "Chris Johnson",
      "domain": ["iot"],
      "kiitemail": "chrisjohnson18@kiit.ac.in",
      "email": "chris.johnson@gmail.com",
      "roll": 1234569,
      "gender": "Male",
      "contactNumber": 9876543212,
      "yearOfStudy": "4th",
      "branch": "Electronics and Communication",
      "links": {
        "resume": "https://example.com/resume/chrisjohnson",
        "github": "https://github.com/chrisjohnson",
        "linkdin": "https://linkedin.com/in/chrisjohnson"
      },
      "existSocieties": "Robotics Club",
      "whyElabs": "To explore IoT and work on interdisciplinary projects.",
      "fromWhereYouGotKnow": "Faculty",
      "anythingElse": "Hoping to contribute meaningfully.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Thank you for this opportunity."
    },
    {
      "name": "Alex Taylor",
      "domain": ["gamedevelopment"],
      "kiitemail": "alextaylor18@kiit.ac.in",
      "email": "alex.taylor@gmail.com",
      "roll": 1234570,
      "gender": "Female",
      "contactNumber": 9876543213,
      "yearOfStudy": "1st",
      "branch": "Computer Science",
      "links": {
        "resume": "https://example.com/resume/alextaylor",
        "github": "https://github.com/alextaylor",
        "linkdin": "https://linkedin.com/in/alextaylor"
      },
      "existSocieties": "Gaming Club",
      "whyElabs": "To create immersive gaming experiences and learn with peers.",
      "fromWhereYouGotKnow": "Website",
      "anythingElse": "Passionate about game design.",
      "present": false,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Eager to start my journey at Elabs."
    },
    {
      "name": "Taylor Morgan",
      "domain": ["videoediting"],
      "kiitemail": "taylormorgan18@kiit.ac.in",
      "email": "taylor.morgan@gmail.com",
      "roll": 1234571,
      "gender": "Male",
      "contactNumber": 9876543214,
      "yearOfStudy": "3rd",
      "branch": "Mass Communication",
      "links": {
        "resume": "https://example.com/resume/taylormorgan",
        "github": "https://github.com/taylormorgan",
        "linkdin": "https://linkedin.com/in/taylormorgan"
      },
      "existSocieties": "Film Club",
      "whyElabs": "To hone my video editing skills and create impactful stories.",
      "fromWhereYouGotKnow": "Friends",
      "anythingElse": "Looking forward to collaborating with others.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": true,
      "selectedBy": "Panel A",
      "message": "Thank you for selecting me."
    },
    {
      "name": "Jordan Casey",
      "domain": ["marketing"],
      "kiitemail": "jordancasey18@kiit.ac.in",
      "email": "jordan.casey@gmail.com",
      "roll": 1234572,
      "gender": "Female",
      "contactNumber": 9876543215,
      "yearOfStudy": "4th",
      "branch": "Business Administration",
      "links": {
        "resume": "https://example.com/resume/jordancasey",
        "github": "https://github.com/jordancasey",
        "linkdin": "https://linkedin.com/in/jordancasey"
      },
      "existSocieties": "Marketing Society",
      "whyElabs": "To apply my marketing knowledge in tech-oriented projects.",
      "fromWhereYouGotKnow": "Alumni",
      "anythingElse": "Excited to bring my creative ideas to the team.",
      "present": true,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Looking forward to contributing."
    },
    {
      "name": "John Doe",
      "domain": ["webdevelopment"],
      "kiitemail": "johndoe18@kiit.ac.in",
      "email": "john.doe@gmail.com",
      "roll": 1234567,
      "gender": "Male",
      "contactNumber": 9876543210,
      "yearOfStudy": "2nd",
      "branch": "Computer Science",
      "links": {
        "resume": "https://example.com/resume/johndoe",
        "github": "https://github.com/johndoe",
        "linkdin": "https://linkedin.com/in/johndoe"
      },
      "existSocieties": "None",
      "whyElabs": "To improve my technical skills and work on innovative projects.",
      "fromWhereYouGotKnow": "Social Media",
      "anythingElse": "Looking forward to learning new technologies.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Thank you for considering my application."
    },
    {
      "name": "Jane Smith",
      "domain": ["graphicdesigning"],
      "kiitemail": "janesmith18@kiit.ac.in",
      "email": "jane.smith@gmail.com",
      "roll": 1234568,
      "gender": "Female",
      "contactNumber": 9876543211,
      "yearOfStudy": "3rd",
      "branch": "Information Technology",
      "links": {
        "resume": "https://example.com/resume/janesmith",
        "github": "https://github.com/janesmith",
        "linkdin": "https://linkedin.com/in/janesmith"
      },
      "existSocieties": "Art Society",
      "whyElabs": "To contribute my design skills and collaborate with others.",
      "fromWhereYouGotKnow": "Friends",
      "anythingElse": "Excited to join and learn!",
      "present": true,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Looking forward to hearing from you."
    },
    {
      "name": "Chris Johnson",
      "domain": ["iot"],
      "kiitemail": "chrisjohnson18@kiit.ac.in",
      "email": "chris.johnson@gmail.com",
      "roll": 1234569,
      "gender": "Male",
      "contactNumber": 9876543212,
      "yearOfStudy": "4th",
      "branch": "Electronics and Communication",
      "links": {
        "resume": "https://example.com/resume/chrisjohnson",
        "github": "https://github.com/chrisjohnson",
        "linkdin": "https://linkedin.com/in/chrisjohnson"
      },
      "existSocieties": "Robotics Club",
      "whyElabs": "To explore IoT and work on interdisciplinary projects.",
      "fromWhereYouGotKnow": "Faculty",
      "anythingElse": "Hoping to contribute meaningfully.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Thank you for this opportunity."
    },
    {
      "name": "Alex Taylor",
      "domain": ["gamedevelopment"],
      "kiitemail": "alextaylor18@kiit.ac.in",
      "email": "alex.taylor@gmail.com",
      "roll": 1234570,
      "gender": "Female",
      "contactNumber": 9876543213,
      "yearOfStudy": "1st",
      "branch": "Computer Science",
      "links": {
        "resume": "https://example.com/resume/alextaylor",
        "github": "https://github.com/alextaylor",
        "linkdin": "https://linkedin.com/in/alextaylor"
      },
      "existSocieties": "Gaming Club",
      "whyElabs": "To create immersive gaming experiences and learn with peers.",
      "fromWhereYouGotKnow": "Website",
      "anythingElse": "Passionate about game design.",
      "present": false,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Eager to start my journey at Elabs."
    },
    {
      "name": "Taylor Morgan",
      "domain": ["videoediting"],
      "kiitemail": "taylormorgan18@kiit.ac.in",
      "email": "taylor.morgan@gmail.com",
      "roll": 1234571,
      "gender": "Male",
      "contactNumber": 9876543214,
      "yearOfStudy": "3rd",
      "branch": "Mass Communication",
      "links": {
        "resume": "https://example.com/resume/taylormorgan",
        "github": "https://github.com/taylormorgan",
        "linkdin": "https://linkedin.com/in/taylormorgan"
      },
      "existSocieties": "Film Club",
      "whyElabs": "To hone my video editing skills and create impactful stories.",
      "fromWhereYouGotKnow": "Friends",
      "anythingElse": "Looking forward to collaborating with others.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": true,
      "selectedBy": "Panel A",
      "message": "Thank you for selecting me."
    },
    {
      "name": "Jordan Casey",
      "domain": ["marketing"],
      "kiitemail": "jordancasey18@kiit.ac.in",
      "email": "jordan.casey@gmail.com",
      "roll": 1234572,
      "gender": "Female",
      "contactNumber": 9876543215,
      "yearOfStudy": "4th",
      "branch": "Business Administration",
      "links": {
        "resume": "https://example.com/resume/jordancasey",
        "github": "https://github.com/jordancasey",
        "linkdin": "https://linkedin.com/in/jordancasey"
      },
      "existSocieties": "Marketing Society",
      "whyElabs": "To apply my marketing knowledge in tech-oriented projects.",
      "fromWhereYouGotKnow": "Alumni",
      "anythingElse": "Excited to bring my creative ideas to the team.",
      "present": true,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Looking forward to contributing."
    },
    {
      "name": "John Doe",
      "domain": ["webdevelopment"],
      "kiitemail": "johndoe18@kiit.ac.in",
      "email": "john.doe@gmail.com",
      "roll": 1234567,
      "gender": "Male",
      "contactNumber": 9876543210,
      "yearOfStudy": "2nd",
      "branch": "Computer Science",
      "links": {
        "resume": "https://example.com/resume/johndoe",
        "github": "https://github.com/johndoe",
        "linkdin": "https://linkedin.com/in/johndoe"
      },
      "existSocieties": "None",
      "whyElabs": "To improve my technical skills and work on innovative projects.",
      "fromWhereYouGotKnow": "Social Media",
      "anythingElse": "Looking forward to learning new technologies.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Thank you for considering my application."
    },
    {
      "name": "Jane Smith",
      "domain": ["graphicdesigning"],
      "kiitemail": "janesmith18@kiit.ac.in",
      "email": "jane.smith@gmail.com",
      "roll": 1234568,
      "gender": "Female",
      "contactNumber": 9876543211,
      "yearOfStudy": "3rd",
      "branch": "Information Technology",
      "links": {
        "resume": "https://example.com/resume/janesmith",
        "github": "https://github.com/janesmith",
        "linkdin": "https://linkedin.com/in/janesmith"
      },
      "existSocieties": "Art Society",
      "whyElabs": "To contribute my design skills and collaborate with others.",
      "fromWhereYouGotKnow": "Friends",
      "anythingElse": "Excited to join and learn!",
      "present": true,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Looking forward to hearing from you."
    },
    {
      "name": "Chris Johnson",
      "domain": ["iot"],
      "kiitemail": "chrisjohnson18@kiit.ac.in",
      "email": "chris.johnson@gmail.com",
      "roll": 1234569,
      "gender": "Male",
      "contactNumber": 9876543212,
      "yearOfStudy": "4th",
      "branch": "Electronics and Communication",
      "links": {
        "resume": "https://example.com/resume/chrisjohnson",
        "github": "https://github.com/chrisjohnson",
        "linkdin": "https://linkedin.com/in/chrisjohnson"
      },
      "existSocieties": "Robotics Club",
      "whyElabs": "To explore IoT and work on interdisciplinary projects.",
      "fromWhereYouGotKnow": "Faculty",
      "anythingElse": "Hoping to contribute meaningfully.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Thank you for this opportunity."
    },
    {
      "name": "Alex Taylor",
      "domain": ["gamedevelopment"],
      "kiitemail": "alextaylor18@kiit.ac.in",
      "email": "alex.taylor@gmail.com",
      "roll": 1234570,
      "gender": "Female",
      "contactNumber": 9876543213,
      "yearOfStudy": "1st",
      "branch": "Computer Science",
      "links": {
        "resume": "https://example.com/resume/alextaylor",
        "github": "https://github.com/alextaylor",
        "linkdin": "https://linkedin.com/in/alextaylor"
      },
      "existSocieties": "Gaming Club",
      "whyElabs": "To create immersive gaming experiences and learn with peers.",
      "fromWhereYouGotKnow": "Website",
      "anythingElse": "Passionate about game design.",
      "present": false,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Eager to start my journey at Elabs."
    },
    {
      "name": "Taylor Morgan",
      "domain": ["videoediting"],
      "kiitemail": "taylormorgan18@kiit.ac.in",
      "email": "taylor.morgan@gmail.com",
      "roll": 1234571,
      "gender": "Male",
      "contactNumber": 9876543214,
      "yearOfStudy": "3rd",
      "branch": "Mass Communication",
      "links": {
        "resume": "https://example.com/resume/taylormorgan",
        "github": "https://github.com/taylormorgan",
        "linkdin": "https://linkedin.com/in/taylormorgan"
      },
      "existSocieties": "Film Club",
      "whyElabs": "To hone my video editing skills and create impactful stories.",
      "fromWhereYouGotKnow": "Friends",
      "anythingElse": "Looking forward to collaborating with others.",
      "present": true,
      "interviewed": false,
      "isinterviewRunning": false,
      "selected": true,
      "selectedBy": "Panel A",
      "message": "Thank you for selecting me."
    },
    {
      "name": "Jordan Casey",
      "domain": ["marketing"],
      "kiitemail": "jordancasey18@kiit.ac.in",
      "email": "jordan.casey@gmail.com",
      "roll": 1234572,
      "gender": "Female",
      "contactNumber": 9876543215,
      "yearOfStudy": "4th",
      "branch": "Business Administration",
      "links": {
        "resume": "https://example.com/resume/jordancasey",
        "github": "https://github.com/jordancasey",
        "linkdin": "https://linkedin.com/in/jordancasey"
      },
      "existSocieties": "Marketing Society",
      "whyElabs": "To apply my marketing knowledge in tech-oriented projects.",
      "fromWhereYouGotKnow": "Alumni",
      "anythingElse": "Excited to bring my creative ideas to the team.",
      "present": true,
      "interviewed": true,
      "isinterviewRunning": false,
      "selected": false,
      "selectedBy": "",
      "message": "Looking forward to contributing."
    },
    
  ]