const candidates: any[] = [
  {
    "name": "Timothy Armstrong",
    "domain": "uiux",
    "kiitemail": "student1@kiit.ac.in",
    "email": "terrance60@gmail.com",
    "roll": "2160672",
    "gender": "Female",
    "contactNumber": "191-106-43",
    "yearOfStudy": "4th",
    "branch": "Educational psychologist",
    "links": {
      "resume": "http://boyd.com/",
      "github": "http://hubbard.com/",
      "linkedin": "http://www.martin.com/"
    },
    "existSocieties": "hand",
    "whyElabs": "Little establish board stock somebody city organization.",
    "fromWhereYouGotKnow": "Strategy parent traditional generation over walk.",
    "anythingElse": "Take probably charge rule.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Jeffrey Macias",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Carolyn Ortiz",
    "message": "National success machine seat five with away."
  },
  {
    "name": "Christopher King",
    "domain": "webdevelopment",
    "kiitemail": "student2@kiit.ac.in",
    "email": "hwise@finley.com",
    "roll": "2198449",
    "gender": "Female",
    "contactNumber": "(348)809-2",
    "yearOfStudy": "2nd",
    "branch": "Programme researcher, broadcasting/film/video",
    "links": {
      "resume": "http://www.bennett-bryan.info/",
      "github": "http://www.nguyen.com/",
      "linkedin": "http://robbins.com/"
    },
    "existSocieties": "recent",
    "whyElabs": "Miss plant put statement break doctor.",
    "fromWhereYouGotKnow": "Eight research message day structure question meeting.",
    "anythingElse": "Debate beat product exist term.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Amy Lopez",
    "isinterviewRunning": true,
    "selected": false,
    "selectedBy": "Sean Parker",
    "message": "Thank face just but."
  },
  {
    "name": "Daniel Lane",
    "domain": "uiux",
    "kiitemail": "student3@kiit.ac.in",
    "email": "kimberlynash@yahoo.com",
    "roll": "2160747",
    "gender": "Male",
    "contactNumber": "975-617-90",
    "yearOfStudy": "4th",
    "branch": "Writer",
    "links": {
      "resume": "http://harrison-snyder.info/",
      "github": "https://www.juarez-reed.com/",
      "linkedin": "https://forbes.com/"
    },
    "existSocieties": "occur",
    "whyElabs": "Better guy idea want.",
    "fromWhereYouGotKnow": "Fast edge central yes it visit picture.",
    "anythingElse": "Set guy hard mean prove stand become.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "Joseph Morales",
    "isinterviewRunning": true,
    "selected": false,
    "selectedBy": "Rebecca Jones",
    "message": "Per probably subject ahead win per every."
  },
  {
    "name": "Marcia White",
    "domain": "appdevelopment",
    "kiitemail": "student4@kiit.ac.in",
    "email": "jimenezjessica@hotmail.com",
    "roll": "2155984",
    "gender": "Male",
    "contactNumber": "(215)467-4",
    "yearOfStudy": "4th",
    "branch": "Health and safety inspector",
    "links": {
      "resume": "http://www.simmons-erickson.com/",
      "github": "http://www.dalton.com/",
      "linkedin": "https://garcia.com/"
    },
    "existSocieties": "off",
    "whyElabs": "Other effort rather provide eye.",
    "fromWhereYouGotKnow": "Sell leader want land bill.",
    "anythingElse": "Agent point education top audience.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "Robert Zuniga",
    "isinterviewRunning": true,
    "selected": false,
    "selectedBy": "Randall Martin",
    "message": "Scientist important turn street commercial."
  },
  {
    "name": "Rebecca Reid",
    "domain": "webdevelopment",
    "kiitemail": "student5@kiit.ac.in",
    "email": "cassidy21@roberts.com",
    "roll": "2170757",
    "gender": "Female",
    "contactNumber": "+1-117-424",
    "yearOfStudy": "4th",
    "branch": "Pensions consultant",
    "links": {
      "resume": "https://www.spencer.info/",
      "github": "http://jones.com/",
      "linkedin": "http://ramsey-ortiz.com/"
    },
    "existSocieties": "task",
    "whyElabs": "Determine guy throw weight increase stand accept plant.",
    "fromWhereYouGotKnow": "Nature performance per design resource per.",
    "anythingElse": "Hope hot look billion experience third man guess.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "Steven Cherry",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Sabrina Atkins",
    "message": "Organization maintain husband their amount end."
  },
  {
    "name": "Christine Martinez",
    "domain": "webdevelopment",
    "kiitemail": "student6@kiit.ac.in",
    "email": "emartinez@coleman.com",
    "roll": "2168889",
    "gender": "Female",
    "contactNumber": "186.953.85",
    "yearOfStudy": "1st",
    "branch": "Computer games developer",
    "links": {
      "resume": "https://ayers-martin.com/",
      "github": "http://gutierrez.net/",
      "linkedin": "http://stokes.com/"
    },
    "existSocieties": "also",
    "whyElabs": "Democratic sea ground song must growth everything.",
    "fromWhereYouGotKnow": "Pretty because within decide computer.",
    "anythingElse": "In fall maybe month.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Michael James",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Steven Cherry",
    "message": "Whom explain agency."
  },
  {
    "name": "Alicia Lopez",
    "domain": "appdevelopment",
    "kiitemail": "student7@kiit.ac.in",
    "email": "jordancynthia@graham-benson.com",
    "roll": "2137314",
    "gender": "Male",
    "contactNumber": "001-865-02",
    "yearOfStudy": "1st",
    "branch": "Veterinary surgeon",
    "links": {
      "resume": "https://little.com/",
      "github": "http://rosario-young.com/",
      "linkedin": "https://www.espinoza.com/"
    },
    "existSocieties": "able",
    "whyElabs": "Identify direction chair wide authority try today.",
    "fromWhereYouGotKnow": "Yet successful former what care receive information.",
    "anythingElse": "Office give pay throughout do.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Todd Shields",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "David Ramirez",
    "message": "Yes from mission laugh hot candidate."
  },
  {
    "name": "Shannon Mitchell",
    "domain": "uiux",
    "kiitemail": "student8@kiit.ac.in",
    "email": "ldaniels@wallace-henderson.info",
    "roll": "2199040",
    "gender": "Female",
    "contactNumber": "+1-397-482",
    "yearOfStudy": "1st",
    "branch": "Immunologist",
    "links": {
      "resume": "http://taylor-payne.biz/",
      "github": "https://www.diaz.com/",
      "linkedin": "http://www.walker-hill.info/"
    },
    "existSocieties": "high",
    "whyElabs": "Finish dark again.",
    "fromWhereYouGotKnow": "Leader use high.",
    "anythingElse": "Represent investment star west inside.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Catherine Jordan",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Brian Randall",
    "message": "Another film next must environment suggest."
  },
  {
    "name": "Jason Davis",
    "domain": "appdevelopment",
    "kiitemail": "student9@kiit.ac.in",
    "email": "ayersashlee@gmail.com",
    "roll": "2152574",
    "gender": "Male",
    "contactNumber": "001-871-10",
    "yearOfStudy": "4th",
    "branch": "Multimedia specialist",
    "links": {
      "resume": "https://adams.com/",
      "github": "https://garcia.com/",
      "linkedin": "http://www.davis-hardy.com/"
    },
    "existSocieties": "mind",
    "whyElabs": "Strategy fact draw heart measure.",
    "fromWhereYouGotKnow": "Next score election major behind.",
    "anythingElse": "Movie nearly development across particular east.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Brianna Hernandez",
    "isinterviewRunning": false,
    "selected": true,
    "selectedBy": "Tanya Johnson",
    "message": "Most mother tree agent card yard."
  },
  {
    "name": "Julie Flores",
    "domain": "appdevelopment",
    "kiitemail": "student10@kiit.ac.in",
    "email": "rbaker@cook.org",
    "roll": "2192666",
    "gender": "Male",
    "contactNumber": "569.426.73",
    "yearOfStudy": "3rd",
    "branch": "Chief Executive Officer",
    "links": {
      "resume": "https://rogers.com/",
      "github": "http://www.clark.info/",
      "linkedin": "http://pope-blackwell.biz/"
    },
    "existSocieties": "financial",
    "whyElabs": "Section development that during work fill everybody.",
    "fromWhereYouGotKnow": "Sell kind that phone maintain break capital.",
    "anythingElse": "Pretty minute through ahead rule number require.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "Jennifer Rose",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Jacob Schneider",
    "message": "Machine assume look first Republican might view."
  },
  {
    "name": "Amy Williams",
    "domain": "webdevelopment",
    "kiitemail": "student11@kiit.ac.in",
    "email": "pamela17@hotmail.com",
    "roll": "2142367",
    "gender": "Male",
    "contactNumber": "818-464-64",
    "yearOfStudy": "1st",
    "branch": "Psychiatric nurse",
    "links": {
      "resume": "https://www.lee.info/",
      "github": "http://www.alvarado.com/",
      "linkedin": "http://www.harvey-garrison.org/"
    },
    "existSocieties": "kid",
    "whyElabs": "Hair add stop tax party stock.",
    "fromWhereYouGotKnow": "Maintain stock upon thus.",
    "anythingElse": "View young happen technology know.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Matthew Jones",
    "isinterviewRunning": true,
    "selected": false,
    "selectedBy": "Laura Todd MD",
    "message": "Force base cultural either lot board support."
  },
  {
    "name": "Theresa Ryan",
    "domain": "appdevelopment",
    "kiitemail": "student12@kiit.ac.in",
    "email": "tuckermartin@yahoo.com",
    "roll": "2112426",
    "gender": "Female",
    "contactNumber": "+1-957-319",
    "yearOfStudy": "2nd",
    "branch": "Marketing executive",
    "links": {
      "resume": "https://hoover.biz/",
      "github": "https://hines.org/",
      "linkedin": "http://carter-peterson.info/"
    },
    "existSocieties": "feel",
    "whyElabs": "True challenge successful look debate foreign.",
    "fromWhereYouGotKnow": "Compare kind kind market.",
    "anythingElse": "Stage news wife actually away tend.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "Amanda Brown",
    "isinterviewRunning": false,
    "selected": true,
    "selectedBy": "Mary Tyler",
    "message": "Down firm person stuff station management professional order."
  },
  {
    "name": "Katherine Jones",
    "domain": "aiml",
    "kiitemail": "student13@kiit.ac.in",
    "email": "joshua29@landry.net",
    "roll": "2167041",
    "gender": "Female",
    "contactNumber": "2252312495",
    "yearOfStudy": "1st",
    "branch": "Psychotherapist, dance movement",
    "links": {
      "resume": "https://smith-martin.com/",
      "github": "http://www.goodman-harris.biz/",
      "linkedin": "https://watkins.org/"
    },
    "existSocieties": "play",
    "whyElabs": "Ten manager you dark past.",
    "fromWhereYouGotKnow": "Result sometimes assume say where magazine church him.",
    "anythingElse": "Will plant article major.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Amanda Crawford",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Scott Barton",
    "message": "Nice war live hundred role pressure industry always."
  },
  {
    "name": "Dr. Jonathan Eaton PhD",
    "domain": "uiux",
    "kiitemail": "student14@kiit.ac.in",
    "email": "ashleybrown@rodriguez.com",
    "roll": "2159410",
    "gender": "Male",
    "contactNumber": "(073)047-6",
    "yearOfStudy": "2nd",
    "branch": "Archivist",
    "links": {
      "resume": "https://www.byrd.com/",
      "github": "https://white.com/",
      "linkedin": "https://www.thomas.info/"
    },
    "existSocieties": "Democrat",
    "whyElabs": "Ever move carry support.",
    "fromWhereYouGotKnow": "Vote three brother sport.",
    "anythingElse": "Force clearly work.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "Gwendolyn Barker",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Kristine Reed",
    "message": "Two president politics north than forward trial."
  },
  {
    "name": "Katherine Parker",
    "domain": "webdevelopment",
    "kiitemail": "student15@kiit.ac.in",
    "email": "johnsonmark@hotmail.com",
    "roll": "2134613",
    "gender": "Female",
    "contactNumber": "(228)529-5",
    "yearOfStudy": "2nd",
    "branch": "Television floor manager",
    "links": {
      "resume": "https://lee.com/",
      "github": "https://www.lucas-hunt.info/",
      "linkedin": "http://waters.com/"
    },
    "existSocieties": "radio",
    "whyElabs": "Detail development resource event pretty.",
    "fromWhereYouGotKnow": "Kid too set growth.",
    "anythingElse": "These summer him leg bit none opportunity.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Christopher Walter",
    "isinterviewRunning": false,
    "selected": true,
    "selectedBy": "Shelly Burton",
    "message": "Wind last street father."
  },
  {
    "name": "Kaylee Nash",
    "domain": "appdevelopment",
    "kiitemail": "student16@kiit.ac.in",
    "email": "gregorydavid@jones.org",
    "roll": "2198850",
    "gender": "Male",
    "contactNumber": "068.906.88",
    "yearOfStudy": "3rd",
    "branch": "Administrator",
    "links": {
      "resume": "https://www.warner-johnson.net/",
      "github": "https://www.dorsey.biz/",
      "linkedin": "http://williamson-flores.com/"
    },
    "existSocieties": "entire",
    "whyElabs": "Offer next but different song which than.",
    "fromWhereYouGotKnow": "Very quite billion effort senior.",
    "anythingElse": "Necessary should how.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Jeffrey Moore",
    "isinterviewRunning": true,
    "selected": false,
    "selectedBy": "Sara Shepard",
    "message": "Those arrive team particularly simple issue risk guess."
  },
  {
    "name": "Darius Long",
    "domain": "aiml",
    "kiitemail": "student17@kiit.ac.in",
    "email": "wendy91@johnson.info",
    "roll": "2125057",
    "gender": "Male",
    "contactNumber": "+1-473-616",
    "yearOfStudy": "2nd",
    "branch": "Adult guidance worker",
    "links": {
      "resume": "https://tucker.info/",
      "github": "http://www.arnold-dominguez.biz/",
      "linkedin": "https://finley.com/"
    },
    "existSocieties": "soldier",
    "whyElabs": "Officer none direction involve.",
    "fromWhereYouGotKnow": "Side yeah economic audience capital tree company.",
    "anythingElse": "Involve attention want spend ready least prepare radio.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Aaron Strickland",
    "isinterviewRunning": true,
    "selected": false,
    "selectedBy": "Michael Hudson",
    "message": "Instead personal national career Democrat project."
  },
  {
    "name": "Timothy Coleman",
    "domain": "webdevelopment",
    "kiitemail": "student18@kiit.ac.in",
    "email": "bensonjames@hotmail.com",
    "roll": "2174766",
    "gender": "Male",
    "contactNumber": "8857213447",
    "yearOfStudy": "3rd",
    "branch": "Dancer",
    "links": {
      "resume": "http://vaughn-goodwin.com/",
      "github": "https://www.johnson-carey.info/",
      "linkedin": "http://www.ibarra-cochran.com/"
    },
    "existSocieties": "control",
    "whyElabs": "Join change sort play various past dog.",
    "fromWhereYouGotKnow": "Major in likely investment author across expert.",
    "anythingElse": "Once likely under.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Tyler Lynch",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Valerie Anderson",
    "message": "Table since than become evening successful."
  },
  {
    "name": "David Shaw",
    "domain": "appdevelopment",
    "kiitemail": "student19@kiit.ac.in",
    "email": "dorothymendez@brown.net",
    "roll": "2159963",
    "gender": "Male",
    "contactNumber": "023-477-48",
    "yearOfStudy": "2nd",
    "branch": "Writer",
    "links": {
      "resume": "http://hinton-jarvis.com/",
      "github": "https://graham.com/",
      "linkedin": "https://www.lewis.net/"
    },
    "existSocieties": "word",
    "whyElabs": "Sign president sea PM.",
    "fromWhereYouGotKnow": "Thank world organization dream dog like finish.",
    "anythingElse": "Officer kid identify responsibility.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "James Parker",
    "isinterviewRunning": false,
    "selected": true,
    "selectedBy": "Robert Terrell",
    "message": "Help series crime stuff professional."
  },
  {
    "name": "Kimberly Dawson",
    "domain": "aiml",
    "kiitemail": "student20@kiit.ac.in",
    "email": "tara25@gmail.com",
    "roll": "2187419",
    "gender": "Male",
    "contactNumber": "+1-167-726",
    "yearOfStudy": "2nd",
    "branch": "Copy",
    "links": {
      "resume": "http://price.com/",
      "github": "https://grant.com/",
      "linkedin": "https://stevens-walker.com/"
    },
    "existSocieties": "usually",
    "whyElabs": "Situation long paper military.",
    "fromWhereYouGotKnow": "Billion once family us time much.",
    "anythingElse": "Beautiful itself be sea.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "Jesse Campbell",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Kristin Peterson",
    "message": "Head daughter maintain learn work."
  },
  {
    "name": "Samantha Snyder",
    "domain": "uiux",
    "kiitemail": "student21@kiit.ac.in",
    "email": "samuelmyers@brown.net",
    "roll": "2157071",
    "gender": "Male",
    "contactNumber": "001-447-64",
    "yearOfStudy": "3rd",
    "branch": "Solicitor, Scotland",
    "links": {
      "resume": "https://www.gonzales-joseph.com/",
      "github": "https://perez-johnson.com/",
      "linkedin": "http://www.baldwin-hall.com/"
    },
    "existSocieties": "budget",
    "whyElabs": "Skin though style animal talk.",
    "fromWhereYouGotKnow": "Seat smile station up and memory adult land.",
    "anythingElse": "Market car turn war.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "Rhonda Sherman",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Andrew Vincent",
    "message": "Soon oil open source itself lay."
  },
  {
    "name": "Sharon Roberson PhD",
    "domain": "webdevelopment",
    "kiitemail": "student22@kiit.ac.in",
    "email": "bryanweeks@francis.com",
    "roll": "2154466",
    "gender": "Female",
    "contactNumber": "(033)230-3",
    "yearOfStudy": "4th",
    "branch": "Engineer, production",
    "links": {
      "resume": "http://hill.info/",
      "github": "http://www.horton-mccoy.com/",
      "linkedin": "https://cox-hall.org/"
    },
    "existSocieties": "pass",
    "whyElabs": "Develop little five clearly address off.",
    "fromWhereYouGotKnow": "I prove team quality bag ever.",
    "anythingElse": "Help help each want catch wall word cover.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "David Williams",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Mason Moore",
    "message": "That including war successful."
  },
  {
    "name": "Emily Herrera",
    "domain": "uiux",
    "kiitemail": "student23@kiit.ac.in",
    "email": "gcrawford@gmail.com",
    "roll": "2161534",
    "gender": "Female",
    "contactNumber": "472.289.53",
    "yearOfStudy": "3rd",
    "branch": "Textile designer",
    "links": {
      "resume": "http://www.smith.org/",
      "github": "https://meyer.com/",
      "linkedin": "https://morris.net/"
    },
    "existSocieties": "money",
    "whyElabs": "Throw leg meeting image.",
    "fromWhereYouGotKnow": "Common letter huge take nearly.",
    "anythingElse": "Religious admit rest throw quickly serious establish personal.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Evan Long",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Mary Haynes",
    "message": "All manager include there effect behind."
  },
  {
    "name": "Timothy Ramos",
    "domain": "uiux",
    "kiitemail": "student24@kiit.ac.in",
    "email": "kenneth53@johnson.net",
    "roll": "2167678",
    "gender": "Male",
    "contactNumber": "528-367-31",
    "yearOfStudy": "4th",
    "branch": "Computer games developer",
    "links": {
      "resume": "http://www.miller-simon.net/",
      "github": "https://www.fisher.com/",
      "linkedin": "https://www.david.com/"
    },
    "existSocieties": "little",
    "whyElabs": "Her shoulder power who figure positive.",
    "fromWhereYouGotKnow": "Quite should agreement second.",
    "anythingElse": "Work true author computer phone data store.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "Kayla Shaw",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Michael Mcpherson",
    "message": "Pretty present and degree public movement production any."
  },
  {
    "name": "Kevin Hall",
    "domain": "webdevelopment",
    "kiitemail": "student25@kiit.ac.in",
    "email": "osandoval@yahoo.com",
    "roll": "2126691",
    "gender": "Female",
    "contactNumber": "(953)424-4",
    "yearOfStudy": "3rd",
    "branch": "Doctor, hospital",
    "links": {
      "resume": "http://floyd.com/",
      "github": "http://harris.com/",
      "linkedin": "http://www.mitchell-gomez.com/"
    },
    "existSocieties": "research",
    "whyElabs": "Development ever responsibility begin word group cold.",
    "fromWhereYouGotKnow": "Exactly page work interest several.",
    "anythingElse": "System star on her control join.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Jonathan Smith",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Bruce Palmer",
    "message": "Suddenly official rather."
  },
  {
    "name": "April Rangel",
    "domain": "uiux",
    "kiitemail": "student26@kiit.ac.in",
    "email": "gibsonemily@gmail.com",
    "roll": "2198659",
    "gender": "Male",
    "contactNumber": "1126698090",
    "yearOfStudy": "1st",
    "branch": "Industrial buyer",
    "links": {
      "resume": "http://jackson.com/",
      "github": "https://perez.info/",
      "linkedin": "http://johnson.com/"
    },
    "existSocieties": "there",
    "whyElabs": "Story service probably.",
    "fromWhereYouGotKnow": "Military be bar data.",
    "anythingElse": "Something marriage behind some at kid option.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Jason Schwartz",
    "isinterviewRunning": true,
    "selected": false,
    "selectedBy": "Daniel Kerr",
    "message": "Occur likely relationship determine soldier."
  },
  {
    "name": "Daniel Marquez",
    "domain": "appdevelopment",
    "kiitemail": "student27@kiit.ac.in",
    "email": "christopher50@hotmail.com",
    "roll": "2159902",
    "gender": "Male",
    "contactNumber": "(542)482-6",
    "yearOfStudy": "2nd",
    "branch": "Multimedia programmer",
    "links": {
      "resume": "http://williamson.com/",
      "github": "http://hernandez.net/",
      "linkedin": "http://www.donovan-martinez.info/"
    },
    "existSocieties": "quality",
    "whyElabs": "Business mouth second follow.",
    "fromWhereYouGotKnow": "Your big many eye tree recently.",
    "anythingElse": "Bit movement my image statement model.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Andrew Walker",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Jonathan Jones",
    "message": "Decade find clearly crime base nice."
  },
  {
    "name": "Carla Conley",
    "domain": "aiml",
    "kiitemail": "student28@kiit.ac.in",
    "email": "melissa29@cummings-edwards.com",
    "roll": "2136368",
    "gender": "Male",
    "contactNumber": "242.964.38",
    "yearOfStudy": "2nd",
    "branch": "Risk analyst",
    "links": {
      "resume": "http://allen.org/",
      "github": "https://mathews.com/",
      "linkedin": "http://www.nolan-mccoy.com/"
    },
    "existSocieties": "prepare",
    "whyElabs": "Seek eat American feel age check those how.",
    "fromWhereYouGotKnow": "Will ten strategy positive go.",
    "anythingElse": "Old court fall hour season skin.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "Thomas Allen",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Kristy Daniels",
    "message": "Contain enough listen rest."
  },
  {
    "name": "Jane Allen",
    "domain": "webdevelopment",
    "kiitemail": "student29@kiit.ac.in",
    "email": "chanhannah@johnson.com",
    "roll": "2153041",
    "gender": "Female",
    "contactNumber": "+1-429-875",
    "yearOfStudy": "1st",
    "branch": "Production manager",
    "links": {
      "resume": "https://www.johnson.com/",
      "github": "https://www.moore.com/",
      "linkedin": "https://gallegos-johnson.com/"
    },
    "existSocieties": "page",
    "whyElabs": "Again people difficult yet account exist each.",
    "fromWhereYouGotKnow": "Along strong push manage.",
    "anythingElse": "Behind what despite feeling industry window six.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "Megan Colon",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Jason Roberts",
    "message": "Early much position player per change."
  },
  {
    "name": "Adam Garcia",
    "domain": "uiux",
    "kiitemail": "student30@kiit.ac.in",
    "email": "mary14@hotmail.com",
    "roll": "2135223",
    "gender": "Male",
    "contactNumber": "+1-487-467",
    "yearOfStudy": "3rd",
    "branch": "Surveyor, building",
    "links": {
      "resume": "https://sharp-larsen.com/",
      "github": "https://torres-castaneda.com/",
      "linkedin": "http://cain.com/"
    },
    "existSocieties": "though",
    "whyElabs": "Tell tough nature actually democratic collection another.",
    "fromWhereYouGotKnow": "Last music call force.",
    "anythingElse": "Cause strategy throw foreign light manager current.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "Robert Wong",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Amber Wilson",
    "message": "Third key old ever you."
  },
  {
    "name": "Samantha Diaz",
    "domain": "uiux",
    "kiitemail": "student31@kiit.ac.in",
    "email": "kmahoney@hotmail.com",
    "roll": "2164785",
    "gender": "Female",
    "contactNumber": "+1-895-889",
    "yearOfStudy": "4th",
    "branch": "Television camera operator",
    "links": {
      "resume": "http://www.quinn-moore.com/",
      "github": "http://gutierrez.com/",
      "linkedin": "https://www.arnold-robinson.info/"
    },
    "existSocieties": "for",
    "whyElabs": "Miss see worker pick community daughter.",
    "fromWhereYouGotKnow": "Seat wife discuss personal.",
    "anythingElse": "Serious military learn training here prove performance.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "Erica Phillips",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Mariah Newton",
    "message": "Large general keep company those."
  },
  {
    "name": "Bruce Fletcher",
    "domain": "appdevelopment",
    "kiitemail": "student32@kiit.ac.in",
    "email": "gomezalex@johnson.com",
    "roll": "2164998",
    "gender": "Female",
    "contactNumber": "+1-048-045",
    "yearOfStudy": "2nd",
    "branch": "Archivist",
    "links": {
      "resume": "http://www.king.com/",
      "github": "http://rice-torres.com/",
      "linkedin": "https://www.evans-farmer.com/"
    },
    "existSocieties": "teacher",
    "whyElabs": "Seat involve air avoid.",
    "fromWhereYouGotKnow": "Local conference another people.",
    "anythingElse": "Increase it speech generation quality without majority.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Angel Wilson",
    "isinterviewRunning": false,
    "selected": true,
    "selectedBy": "Jason Miller",
    "message": "Whatever eat wear board set believe drug."
  },
  {
    "name": "Sharon Beltran",
    "domain": "webdevelopment",
    "kiitemail": "student33@kiit.ac.in",
    "email": "richardmartinez@pierce.com",
    "roll": "2161249",
    "gender": "Male",
    "contactNumber": "(336)735-3",
    "yearOfStudy": "1st",
    "branch": "Volunteer coordinator",
    "links": {
      "resume": "https://moran.com/",
      "github": "http://www.johnson.net/",
      "linkedin": "http://www.li.info/"
    },
    "existSocieties": "water",
    "whyElabs": "Factor what admit partner first.",
    "fromWhereYouGotKnow": "Plan great play forward better with.",
    "anythingElse": "Face economic camera cell machine analysis increase.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "Lori Anderson",
    "isinterviewRunning": false,
    "selected": true,
    "selectedBy": "Dennis Spencer",
    "message": "Very never shake suffer Democrat admit response."
  },
  {
    "name": "Stephanie Rios",
    "domain": "aiml",
    "kiitemail": "student34@kiit.ac.in",
    "email": "richardtimothy@mendez-duke.info",
    "roll": "2114216",
    "gender": "Female",
    "contactNumber": "+1-008-044",
    "yearOfStudy": "3rd",
    "branch": "Petroleum engineer",
    "links": {
      "resume": "http://hahn-zamora.biz/",
      "github": "https://www.guerrero.com/",
      "linkedin": "https://massey.com/"
    },
    "existSocieties": "face",
    "whyElabs": "Whole development after top manager decide success discussion.",
    "fromWhereYouGotKnow": "Case protect citizen instead.",
    "anythingElse": "Let respond close.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Alexander Knight",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Cindy Gutierrez",
    "message": "Quickly now road challenge season father."
  },
  {
    "name": "Alice Brown",
    "domain": "appdevelopment",
    "kiitemail": "student35@kiit.ac.in",
    "email": "jenniferthomas@smith.com",
    "roll": "2196578",
    "gender": "Male",
    "contactNumber": "001-727-08",
    "yearOfStudy": "3rd",
    "branch": "Social worker",
    "links": {
      "resume": "http://peterson.com/",
      "github": "http://gill-singh.com/",
      "linkedin": "https://www.hensley.com/"
    },
    "existSocieties": "Mr",
    "whyElabs": "Decide include friend customer fast meeting hot.",
    "fromWhereYouGotKnow": "Cup per list despite time recognize want.",
    "anythingElse": "Piece as current smile serve wrong material.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Lisa Franco",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Rhonda Mcfarland",
    "message": "Education message see then save next I."
  },
  {
    "name": "Amanda Mendez",
    "domain": "webdevelopment",
    "kiitemail": "student36@kiit.ac.in",
    "email": "eric68@hotmail.com",
    "roll": "2128886",
    "gender": "Female",
    "contactNumber": "171-155-91",
    "yearOfStudy": "2nd",
    "branch": "Restaurant manager, fast food",
    "links": {
      "resume": "https://vaughan.com/",
      "github": "https://www.quinn.com/",
      "linkedin": "https://gregory.com/"
    },
    "existSocieties": "sea",
    "whyElabs": "Fill small end quickly second.",
    "fromWhereYouGotKnow": "Red no eat market wall have.",
    "anythingElse": "Out generation power generation who reflect.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Emily Wilson",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "James Payne Jr.",
    "message": "Others inside general mother."
  },
  {
    "name": "Kimberly Meyer",
    "domain": "webdevelopment",
    "kiitemail": "student37@kiit.ac.in",
    "email": "weeksstephanie@hotmail.com",
    "roll": "2196522",
    "gender": "Male",
    "contactNumber": "506.650.59",
    "yearOfStudy": "4th",
    "branch": "Careers information officer",
    "links": {
      "resume": "https://www.brown.info/",
      "github": "https://www.morrison-harris.com/",
      "linkedin": "https://ross.org/"
    },
    "existSocieties": "poor",
    "whyElabs": "Brother protect here spend.",
    "fromWhereYouGotKnow": "Place west hundred several hotel art.",
    "anythingElse": "Agree company real management.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Wendy Ray",
    "isinterviewRunning": false,
    "selected": true,
    "selectedBy": "Derek Jones",
    "message": "Head environment threat record somebody which."
  },
  {
    "name": "Phillip Riley",
    "domain": "appdevelopment",
    "kiitemail": "student38@kiit.ac.in",
    "email": "vincentcortez@gmail.com",
    "roll": "2138823",
    "gender": "Male",
    "contactNumber": "001-696-36",
    "yearOfStudy": "4th",
    "branch": "Tourist information centre manager",
    "links": {
      "resume": "http://www.miller.com/",
      "github": "http://meyer-flores.com/",
      "linkedin": "http://www.jensen-schwartz.com/"
    },
    "existSocieties": "find",
    "whyElabs": "Call reason author well magazine kid production.",
    "fromWhereYouGotKnow": "Practice after impact wall office.",
    "anythingElse": "Issue discover fight everybody include herself success most.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "Anna Bray",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Gary Hayes",
    "message": "Question reveal offer vote behavior suffer skill."
  },
  {
    "name": "Francisco Daniels",
    "domain": "aiml",
    "kiitemail": "student39@kiit.ac.in",
    "email": "brady04@miller.org",
    "roll": "2141357",
    "gender": "Female",
    "contactNumber": "(048)524-6",
    "yearOfStudy": "4th",
    "branch": "Hydrogeologist",
    "links": {
      "resume": "https://www.hall.com/",
      "github": "https://perez.org/",
      "linkedin": "https://www.eaton-cruz.com/"
    },
    "existSocieties": "plant",
    "whyElabs": "Per chance west month.",
    "fromWhereYouGotKnow": "You member seven day use these war.",
    "anythingElse": "Million how policy trade radio group guy.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "David Jones",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Garrett Henry",
    "message": "One which identify especially statement."
  },
  {
    "name": "Daniel Berry",
    "domain": "webdevelopment",
    "kiitemail": "student40@kiit.ac.in",
    "email": "tiffany49@gmail.com",
    "roll": "2137423",
    "gender": "Male",
    "contactNumber": "001-022-26",
    "yearOfStudy": "3rd",
    "branch": "Fine artist",
    "links": {
      "resume": "https://anderson.com/",
      "github": "https://williams.net/",
      "linkedin": "https://prince.com/"
    },
    "existSocieties": "meeting",
    "whyElabs": "Recently situation like.",
    "fromWhereYouGotKnow": "Indicate particularly get bar.",
    "anythingElse": "Southern indeed bad take child throughout push.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Mary Lowery",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Karen Jacobs",
    "message": "Trouble medical treat discover."
  },
  {
    "name": "Jennifer Allen",
    "domain": "appdevelopment",
    "kiitemail": "student41@kiit.ac.in",
    "email": "smithlisa@yahoo.com",
    "roll": "2185564",
    "gender": "Female",
    "contactNumber": "+1-923-609",
    "yearOfStudy": "4th",
    "branch": "Youth worker",
    "links": {
      "resume": "https://www.vaughn-hill.net/",
      "github": "https://maddox.com/",
      "linkedin": "http://www.jones-swanson.com/"
    },
    "existSocieties": "six",
    "whyElabs": "Training poor baby charge yes visit.",
    "fromWhereYouGotKnow": "On do road bit wish power cause watch.",
    "anythingElse": "Court however exactly rise itself suddenly painting.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Doris Ramirez",
    "isinterviewRunning": true,
    "selected": false,
    "selectedBy": "Christopher Benson",
    "message": "Admit nor hit pull keep and."
  },
  {
    "name": "Stacey Harding",
    "domain": "aiml",
    "kiitemail": "student42@kiit.ac.in",
    "email": "yfritz@stone.com",
    "roll": "2112016",
    "gender": "Female",
    "contactNumber": "0020498950",
    "yearOfStudy": "2nd",
    "branch": "Embryologist, clinical",
    "links": {
      "resume": "http://www.wright.com/",
      "github": "https://www.wilson.com/",
      "linkedin": "http://sparks.com/"
    },
    "existSocieties": "try",
    "whyElabs": "Writer live floor green age say listen.",
    "fromWhereYouGotKnow": "Security difference with.",
    "anythingElse": "Analysis poor suffer security ball entire those.",
    "present": true,
    "interviewed": true,
    "interviewedBy": "Michael Swanson",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Ashley Powers",
    "message": "Spend natural Republican we else onto."
  },
  {
    "name": "Marilyn Rogers",
    "domain": "webdevelopment",
    "kiitemail": "student43@kiit.ac.in",
    "email": "coheneric@chavez.com",
    "roll": "2157611",
    "gender": "Female",
    "contactNumber": "6054574341",
    "yearOfStudy": "3rd",
    "branch": "Energy engineer",
    "links": {
      "resume": "http://www.lewis.com/",
      "github": "http://rasmussen-greer.com/",
      "linkedin": "https://davis.net/"
    },
    "existSocieties": "hit",
    "whyElabs": "Base wind west speak instead.",
    "fromWhereYouGotKnow": "Per bar gun.",
    "anythingElse": "Simple reach human both how never.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "Steven Anderson",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Omar Pratt",
    "message": "Few operation common over seven whether five why."
  },
  {
    "name": "Carla Vazquez",
    "domain": "uiux",
    "kiitemail": "student44@kiit.ac.in",
    "email": "fgardner@gmail.com",
    "roll": "2130208",
    "gender": "Male",
    "contactNumber": "815-149-26",
    "yearOfStudy": "2nd",
    "branch": "Biomedical engineer",
    "links": {
      "resume": "https://park.com/",
      "github": "http://www.stewart-blackwell.com/",
      "linkedin": "http://www.harrington.com/"
    },
    "existSocieties": "window",
    "whyElabs": "World local amount detail safe remain information everybody.",
    "fromWhereYouGotKnow": "Million cold argue ready remain follow finish.",
    "anythingElse": "Top happy yourself administration.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Anthony Reyes",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Mr. Jeffrey Long PhD",
    "message": "Successful shake become keep."
  },
  {
    "name": "Donald Moore",
    "domain": "appdevelopment",
    "kiitemail": "student45@kiit.ac.in",
    "email": "jacqueline39@weiss.biz",
    "roll": "2198460",
    "gender": "Female",
    "contactNumber": "711-334-33",
    "yearOfStudy": "2nd",
    "branch": "Conservation officer, nature",
    "links": {
      "resume": "http://robinson.com/",
      "github": "https://gonzalez.com/",
      "linkedin": "http://smith-black.com/"
    },
    "existSocieties": "entire",
    "whyElabs": "Blood paper into hear capital next.",
    "fromWhereYouGotKnow": "Within mean nothing opportunity.",
    "anythingElse": "Join particular expect short voice.",
    "present": false,
    "interviewed": false,
    "interviewedBy": "Kathleen Liu",
    "isinterviewRunning": false,
    "selected": true,
    "selectedBy": "Amanda Henderson",
    "message": "Just blue check position trouble subject."
  },
  {
    "name": "Michael Mcintosh",
    "domain": "uiux",
    "kiitemail": "student46@kiit.ac.in",
    "email": "brownmatthew@hotmail.com",
    "roll": "2184336",
    "gender": "Female",
    "contactNumber": "(703)655-2",
    "yearOfStudy": "1st",
    "branch": "Scientist, product/process development",
    "links": {
      "resume": "https://brown.com/",
      "github": "http://www.torres-patel.com/",
      "linkedin": "http://www.ball.net/"
    },
    "existSocieties": "finish",
    "whyElabs": "Until allow home travel world front.",
    "fromWhereYouGotKnow": "Exactly whole soon.",
    "anythingElse": "Political else nor floor cup.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "John Mcgrath",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Matthew Vang",
    "message": "State difficult soldier improve accept."
  },
  {
    "name": "Keith Gonzalez",
    "domain": "appdevelopment",
    "kiitemail": "student47@kiit.ac.in",
    "email": "andersonwhitney@yahoo.com",
    "roll": "2161116",
    "gender": "Female",
    "contactNumber": "+1-744-266",
    "yearOfStudy": "1st",
    "branch": "Clinical cytogeneticist",
    "links": {
      "resume": "http://www.jones.com/",
      "github": "https://garcia.com/",
      "linkedin": "https://padilla.org/"
    },
    "existSocieties": "by",
    "whyElabs": "Modern finally recognize question agent board.",
    "fromWhereYouGotKnow": "Usually onto least buy usually pressure pay.",
    "anythingElse": "Social performance support tree factor set.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "David Warner",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Shawn Moore",
    "message": "Thought sell already write catch feeling them."
  },
  {
    "name": "Kimberly Smith",
    "domain": "webdevelopment",
    "kiitemail": "student48@kiit.ac.in",
    "email": "laura99@wright.com",
    "roll": "2187768",
    "gender": "Male",
    "contactNumber": "+1-238-316",
    "yearOfStudy": "4th",
    "branch": "Horticulturist, amenity",
    "links": {
      "resume": "https://ramirez.org/",
      "github": "https://www.morales.biz/",
      "linkedin": "http://silva.com/"
    },
    "existSocieties": "cover",
    "whyElabs": "Suffer way do others.",
    "fromWhereYouGotKnow": "Feel hit become.",
    "anythingElse": "Seven former main agent edge.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Terry James",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Tara Mitchell",
    "message": "Station who government service."
  },
  {
    "name": "David Avila",
    "domain": "uiux",
    "kiitemail": "student49@kiit.ac.in",
    "email": "williamselizabeth@hotmail.com",
    "roll": "2185106",
    "gender": "Female",
    "contactNumber": "1897390328",
    "yearOfStudy": "1st",
    "branch": "Neurosurgeon",
    "links": {
      "resume": "https://phillips.com/",
      "github": "https://www.brown.com/",
      "linkedin": "http://shaw-wilson.com/"
    },
    "existSocieties": "certain",
    "whyElabs": "Customer arrive candidate sport star lose serious.",
    "fromWhereYouGotKnow": "Sit several cover truth quickly can.",
    "anythingElse": "Stay quality government trial quality phone collection.",
    "present": false,
    "interviewed": true,
    "interviewedBy": "Thomas Tapia",
    "isinterviewRunning": false,
    "selected": false,
    "selectedBy": "Dawn Lewis",
    "message": "Notice modern television others."
  },
  {
    "name": "Charles Sandoval",
    "domain": "uiux",
    "kiitemail": "student50@kiit.ac.in",
    "email": "shannonlopez@gmail.com",
    "roll": "2178364",
    "gender": "Male",
    "contactNumber": "+1-558-753",
    "yearOfStudy": "3rd",
    "branch": "Hydrographic surveyor",
    "links": {
      "resume": "http://fox.com/",
      "github": "https://www.johnson.org/",
      "linkedin": "https://www.jordan-forbes.com/"
    },
    "existSocieties": "their",
    "whyElabs": "Attention reveal nothing nation there.",
    "fromWhereYouGotKnow": "Those industry according possible.",
    "anythingElse": "Deal this such lay.",
    "present": true,
    "interviewed": false,
    "interviewedBy": "Mary Thompson",
    "isinterviewRunning": true,
    "selected": true,
    "selectedBy": "Laura Conley",
    "message": "Store site management throughout."
  }
]

export default candidates;
